### ISSUE TITLE
const_fn: feature has been removed

### ISSUE THREAD

**Issue by ms140569** [RusPiRo/ruspiro-arch-aarch64#16]
I'm getting

$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/ruspiro-arch-aarch64-0.1.4/src/lib.rs:10:22
   |
10 | #![feature(llvm_asm, const_fn)]
   |                      ^^^^^^^^ feature has been removed
   |
   = note: split into finer-grained feature gates

when compiling using:

rustc 1.55.0-nightly (7a16cfcff 2021-07-11)

same happens in ruspiro-mmio-register-0.1.2, so i don't double-post it there ... HTH

**Comment by 2ndTaleStudio** [comment]
Hi,

thanks for raising this issue. It happens that I'm kind of behind the actual release schedule of the rust programming language 😊. However, I'll take a look and provide a fix as soon as possible.
